import {generateQuestion,checkAnswer} from './math-engine.js';
const $=id=>document.getElementById(id);let state={i:0,score:0,questions:[],started:0,locked:false};
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
function symbol(op){return ({tambah:'+',tolak:'−',darab:'×',bahagi:'÷'})[op]}
function render(){const q=state.questions[state.i];$('count').textContent=`Soalan ${state.i+1}/10`;$('score').textContent=`Betul ${state.score}`;$('question').textContent=`${q.a} ${symbol(q.operation)} ${q.b} = ?`;show('division',q.operation==='bahagi');show('normal',q.operation!=='bahagi');$('answer').value='';$('quotient').value='';$('remainder').value='';$('feedback').textContent='';$('feedback').className='feedback';show('next',false);show('check',true);state.locked=false;}
function start(){state={i:0,score:0,questions:[],started:Date.now(),locked:false};for(let i=0;i<10;i++)state.questions.push(generateQuestion($('op').value,$('level').value));show('setup',false);show('result',false);show('game',true);render()}
function beep(ok){try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch{}}
function check(){if(state.locked)return;const q=state.questions[state.i];const submitted=q.operation==='bahagi'?{quotient:$('quotient').value,remainder:$('remainder').value}:$('answer').value;const r=checkAnswer(q,submitted);state.locked=true;if(r.correct){state.score++;$('feedback').textContent='✓ Betul! Hebat!';$('feedback').classList.add('good')}else{$('feedback').textContent=`✗ Belum tepat. Jawapan: ${q.operation==='bahagi'?`${r.expected.quotient} baki ${r.expected.remainder}`:r.expected}`;$('feedback').classList.add('bad')}beep(r.correct);show('check',false);show('next',true)}
function next(){if(!state.locked)return;if(state.i<9){state.i++;render();return}const secs=Math.max(1,Math.round((Date.now()-state.started)/1000));const accuracy=state.score*10;show('game',false);show('result',true);$('summary').textContent=`Markah ${state.score}/10 • Ketepatan ${accuracy}% • Masa ${secs} saat`;}
$('start').addEventListener('click',start);$('check').addEventListener('click',check);$('next').addEventListener('click',next);$('again').addEventListener('click',()=>{show('result',false);show('setup',true)});$('answer').addEventListener('keydown',e=>{if(e.key==='Enter')check()});
